### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by mainguyenanhvu** [shakedzy/dython#102]
https://github.com/shakedzy/dython/blob/a2c6048c3d6cfb39a5dff35f6bd40516d22ab07b/dython/model_utils.py#L85

if len(y_pred.shape) != 1, then y_t and y_p will receive list type. 

Please check it.

**Comment by shakedzy** [comment]
Thanks! Fixed in version 0.6.8
