### ISSUE TITLE
Clarification on input data for correlation ratio ?

### ISSUE THREAD

**Issue by anwesha25** [shakedzy/dython#103]
I had cloned your repo and I noticed that you are using **correlation ratio** for finding association between categorical-continuous cases. And you don't really consider which one is **dependent or independent variable** in this case.

So, does that mean the way values of a categorical data(_independent_) influence the outcome of numerical data(_dependent_) is same as the way numerical data(_independent_) influence outcome of categorical data(_dependent_) ??

**Comment by shakedzy** [comment]
Hi @anwesha25 , could you please elaborate on your question? I'm not sure I understand it.

**Comment by anwesha25** [comment]
def **correlation_ratio(categories,
                      measurements,
                      nan_strategy=_REPLACE,
                      nan_replace_value=_DEFAULT_REPLACE_VALUE):**
    """
    Calculates the Correlation Ratio (sometimes marked by the greek letter Eta)
    for categorical-continuous association.
    Answers the question - **given a continuous value of a measurement, is it
    possible to know which category is it associated with?**
    Value is in the range [0,1], where 0 means a category cannot be determined
    by a continuous measurement, and 1 means a category can be determined with
    absolute certainty.
    
**given a continuous value of a measurement, is it possible to know which category is it associated with?**  --> this means that the outcome of the the **categorical data** can be measured by the **continuous measurement**

**_so my question is which correlation measurement test should be considered, to determine outcome of continuous measurement data when values of categorical data is given?_**

I have checked the **associations()** method which you have written, it looked like you consider **correlation ratio** for both above mentioned cases.

**Comment by shakedzy** [comment]
What do you mean by "which correlation measurement"? Could you please provide a concrete example with some data? I don't understand the question..

**Comment by shakedzy** [comment]
Could you please provide examples to showcase the two said cases? I don't understand..

**Comment by anwesha25** [comment]
Okay I am quite new to this domain of statistical analysis. Having said that,
let's consider the case of a person's **salary and whether he has bought a car(yes/no).** 

Now there could be two scenario's 
1. I want to check if **the salary is known**, can I determine **if the person has bought a car**
2. I want to check **if a person has bought a car**, can **I determine his salary**.

what I am trying to understand here is the way **salary effects the outcome of buying a car**, is it the same way **having a car effects someone's salary** ?
should the **correlation_ratio** method only be used in both cases to calculate the association?

**Comment by shakedzy** [comment]
Hi, quoting the docstring you pasted above:

> Answers the question - given a continuous value of a measurement, is it possible to know which category is it associated with?

And so, it answers case #1. For better understanding how this works, I recommend reading about this ratio more. You can begin with it's Wikipedia page.
