### ISSUE TITLE
Unable to find associations for dataset with 40k variables 

### ISSUE THREAD

**Issue by lyrasheu1210** [shakedzy/dython#108]
### Version check:

Run and copy the output:
```python
import sys, dython
print(sys.version_info)
print(dython.__version__)
```

### Describe the bug:

The execution of the code halted and errored as it could not handle 40k variables, I am assuming it is because a matrix of 40k x 40k is too big. Is there a solution to this?
Code to reproduce:
```python
import dython
# your code goes here
```

## Error message:

Error message:
```
```

**Comment by shakedzy** [comment]
Unable to provide solution without data, error message and library version.
