### ISSUE TITLE
The heatmap doesn't scale well

### ISSUE THREAD

**Issue by egor-ryashin** [shakedzy/dython#11]
I attached an example with 56 columns
![image](https://user-images.githubusercontent.com/14215045/57988939-9e401f00-7a9c-11e9-9ceb-177265ba7505.png)

**Comment by shakedzy** [comment]
That has to do with `seaborn` which I use to create the heatmap. You can give `associations` additional parameters which relate to `seaborn` heatmaps and `matplotlib` plots, such as `figsize`, `annot` and `fmt` (see the source code of `associations`, after the `if plot:` line). Use these to change the scale of the heatmap and configure if and how the numbers are printed. 
For additional information regarding these parameters and how to adjust heatmaps, see the `seaborn` documentation.
