### ISSUE TITLE
correlation_ratio returns 1.0000000000002 (does not satisfy 0 <= x <= 1)

### ISSUE THREAD

**Issue by lahdjirayhan** [shakedzy/dython#116]
The following issue is based on the latest, github version of dython on the master branch.

In some rare cases, some functions return values just very slightly outside of its supposed theoretical range, like in the example below. It returns 1.0000000000000002 but theoretically the return values should be in [0, 1]. I very highly suspect this behavior is caused by floating-point rounding problem stuffs, out of our control.

---

`hypothesis` recently found that this example makes a failing test:

```
================================== FAILURES ===================================
_____________________ test_correlation_ratio_value_range ______________________

    @given(c_m = categories_and_measurements())
>   def test_correlation_ratio_value_range(c_m):

tests\test_nominal\test_correlation_ratio.py:21:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

c_m = (['B', 'A', 'A', 'A', 'A', 'A', ...], [3302855032913.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...])

    @given(c_m = categories_and_measurements())
    def test_correlation_ratio_value_range(c_m):
        category, measurement = c_m

        corr_ratio = correlation_ratio(category, measurement)

>       assert 0.0 <= corr_ratio <= 1.0 or np.isnan(corr_ratio)
E       AssertionError: assert (1.0000000000000002 <= 1.0 or False)
E        +  where False = <ufunc 'isnan'>(1.0000000000000002)
E        +    where <ufunc 'isnan'> = np.isnan

tests\test_nominal\test_correlation_ratio.py:26: AssertionError
--------------------------------- Hypothesis ----------------------------------
Falsifying example: test_correlation_ratio_value_range(
    c_m=(['B', 'A', 'A', 'A', 'A', 'A', 'A'],
     [3302855032913.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
)
```

Just to be up front, this floating point problem appears in another test as well, but the test was then written like this to avoid failing similarly.

https://github.com/shakedzy/dython/blob/a4a05846256c813f5275dd0442a508ce0b436dfc/tests/test_nominal/test_cramers_v.py#L33-L43

**Comment by shakedzy** [comment]
Yes, I fixed one of those issue in the last version, due to a failed test:

https://github.com/shakedzy/dython/blob/master/dython/nominal.py#L192-L194

but I haven't considered all the other possible cases..
