### ISSUE TITLE
No heatmap shown

### ISSUE THREAD

**Issue by ninaspreitzer** [shakedzy/dython#129]
When I want to reproduce `associations_mushrooms_example()` the heatmap does not show up in the ouput 
<img width="1216" alt="Screenshot 2022-07-12 at 17 05 35" src="https://user-images.githubusercontent.com/57034840/178523583-36415b2b-c162-4e51-b855-697029a027c3.png">

**Comment by shakedzy** [comment]
what happens when you run `associations_mushrooms_example()`?

**Comment by shakedzy** [comment]
Closing due to no response.
