### ISSUE TITLE
(docs) documentation for `nominal` module not updated on website

### ISSUE THREAD

**Issue by mahieyin-rahmun** [shakedzy/dython#135]
### Describe the bug:

Just a short heads up: I just noticed that the documentation for [`nominal` module](http://shakedzy.xyz/dython/modules/nominal/) was not updated on the website, despite the [markdown file](https://github.com/shakedzy/dython/blob/master/docs/modules/nominal.md) being updated.

![Screenshot of the documentation page](https://user-images.githubusercontent.com/37664921/190339999-76b52c1f-ec22-4cd3-bf1a-61ac6c8b26cf.png)

## Error message:

N/A

## Input data:

N/A

**Comment by shakedzy** [comment]
Hey @mahieyin-rahmun , that's on purpose :) The docs update only after manually running `mkdocs gh-deploy`. I haven't updated it as this new feature is still part of the `dev` version, which is only available by cloning this repo. Once version 0.7.2 is released to PyPi, I'll update the docs.

**Comment by mahieyin-rahmun** [comment]
Ah okay. Thanks for the clarification.
