### ISSUE TITLE
Cramer vs. Theil

### ISSUE THREAD

**Issue by ronyarmon** [shakedzy/dython#146]
Hi, I'm searching for correlations in a very small dataset (26 samples): 
![Screenshot from 2023-02-08 16-36-43](https://user-images.githubusercontent.com/30949452/217560788-79c7818b-aa67-4fa8-b034-403b69422e2e.png)
When calculating the associations I'm getting very different results for the Cramer and Theil tests.  
```
print('Cramer correlations')
cramer_plot = associations(df_cat, nom_nom_assoc='cramer',filename= 'complete_correlation.png',\
                                    figsize=(4,4))
print('Theil correlations')
theil_plot = associations(df_cat, nom_nom_assoc='theil', filename= 'theil_correlation.png', figsize=(4,4))
```
![Screenshot from 2023-02-08 16-45-07](https://user-images.githubusercontent.com/30949452/217562892-454f41f2-6c40-42a1-9610-0cb7dec8da84.png)

Is the difference in their absolute values to be expected? Which test is more valid? I would tend to use Cramer since it's built on the chi-square test which is broadly accepted but wonder if I should use Theil due to the (slight) features asymmetry. I've read the [post](https://towardsdatascience.com/the-search-for-categorical-correlation-a1cf7f1888c9) explaining these methods and wonder what would you recommend in such cases

**Comment by shakedzy** [comment]
Hey @ronyarmon - I recommend to read the [documentation](https://shakedzy.xyz/dython/) about these two measures. They're different and cannot be compared.
If you ask me, I wouldn't choose Cramer's V on such a small dataset. See the method's documentation for more on this.

**Comment by ronyarmon** [comment]
Thanks for your advice, I didn't see a reference to dataset size but will keep exploring
