### ISSUE TITLE
assotications function from pip or conda does not have multiprocessing or max_cpu_core ??

### ISSUE THREAD

**Issue by Nevermetyou65** [shakedzy/dython#149]
Hello

Today I just downloaded this package using pip and conda. What I found is when I use `associations` functions, the exception is raised telling me that there are no `multiprocessing` or `max_cpu_core` arguments.
After that, I used `pip install git+https://github.com/shakedzy/dython.git`, and now I have these args for `associations` function

Could it be that the package on pip or conda are not updated??

thank for good package.

**Comment by shakedzy** [comment]
Closing due to no response
