### ISSUE TITLE
Nominal functions do not handle missing values

### ISSUE THREAD

**Issue by shakedzy** [shakedzy/dython#15]
The `nominal` module was not designed to handle incomplete data. I would like to figure out a solution to this:

- Should all methods accept incomplete data?

- How should methods handle missing data?

**Comment by maximilianbaumann** [comment]
You sould definately add a notice somewhere more visible to make users aware of this behavior.
Or maybe rise a warning or an exception.
I guess the most reasonable solution is to leave handling of missing values to the user.

Also I noticed that `cramers_v` does handle incomplete data as long as the confusion matrix still having more than one distinct value in each dimension.

**Comment by shakedzy** [comment]
@maximilianbaumann please feel free to add it and create a pull request

**Comment by shakedzy** [comment]
As of version 0.3.0, the `nominal` module now supports missing values (such as `None` and `np.nan`)
