### ISSUE TITLE
Add official support for Python 3.12

### ISSUE THREAD

**Issue by shakedzy** [shakedzy/dython#155]
As Python 3.12 was released, `dython` needs to be tested for it too.

**Comment by Pesche007** [comment]
Thanks for your work. 

Just upgraded to Python 3 (running Pandas 2.1.1) and some future warings pop up

`import pandas as pd
from sklearn import datasets
from dython.nominal import associations

# Load data 
iris = datasets.load_iris()

# Convert int classes to strings to allow associations 
# method to automatically recognize categorical columns
target = ['C{}'.format(i) for i in iris.target]

# Prepare data
X = pd.DataFrame(data=iris.data, columns=iris.feature_names)
y = pd.DataFrame(data=target, columns=['target'])
df = pd.concat([X, y], axis=1)

# Plot features associations
associations(df)`

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\dython\nominal.py:708: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  inf_nan.loc[columns[i], columns[j]] = _inf_nan_str(ij)
C:\Users\User\AppData\Roaming\Python\Python310\site-packages\dython\nominal.py:709: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  inf_nan.loc[columns[j], columns[i]] = _inf_nan_str(ji)

**Comment by shakedzy** [comment]
@Pesche007 this seems to be a bug in Pandas, which was solved in version 2.1.2: https://github.com/pandas-dev/pandas/issues/55025
Try upgrading Pandas and see if it is solved.
