### ISSUE TITLE
ImportError: cannot import name 'interp' from 'scipy'

### ISSUE THREAD

**Issue by turlog** [shakedzy/dython#156]
* dython==0.7.4
* python==3.12

Cannot import module:
```
>>> import sys, dython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../dython/__init__.py", line 1, in <module>
    from . import nominal, model_utils, sampling, data_utils
  File ".../dython/model_utils.py", line 4, in <module>
    from scikitplot.helpers import binary_ks_curve
  File ".../scikitplot/__init__.py", line 2, in <module>
    from . import metrics, cluster, decomposition, estimators
  File ".../scikitplot/metrics.py", line 27, in <module>
    from scipy import interp
ImportError: cannot import name 'interp' from 'scipy' (...)
```
As you can see exception is raised in `scikitplot` which is not maintained (last commits in 2018).
Current workaround is to pin `scipy<1.12`.

**Comment by shakedzy** [comment]
Hey @turlog , I think you figured out the issue - I need to drop the dependency on scikit-plot. It's required only for one function, so I guess it shouldn't be too complicated.

**Comment by shakedzy** [comment]
A fix is available in `0.7.5.dev`, you can currently install this from source. Version ;0ץ7ץ; will be published to PyPi in the next following days

**Comment by turlog** [comment]
@shakedzy thanks a lot, I appreciate quick reaction :)

**Comment by shakedzy** [comment]
Version 0.7.5 has been published to PyPi
