### ISSUE TITLE
Customize heatmap size

### ISSUE THREAD

**Issue by neongreen13** [shakedzy/dython#18]
Thanks for this amazing categorical correlation matrix using Cramer's V and Theil's U! I'm working in Jupyter Notebook and the heat map is very small and I can't read all the categories. I'm learning on the mushroom dataset and want to plot all features, like you did in your article.

My code:
```
column_names = ['class','cap-shape','cap-surface','cap-color','bruises?','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']

import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
df = pd.read_csv(url, header=None, names=column_names)
df.drop(columns=['veil-type'], inplace=True)

from dython import nominal
nominal.associations(df, theil_u=True, nominal_columns='all')
```
Is there a way to display the heat map larger in Jupyter Notebook? Thanks for creating this!

**Comment by shakedzy** [comment]
Hi, yes - you can pass `figsize=(10,10)` (or any other numbers) to `associations`. You can also pass [seaborn heatmap's](https://seaborn.pydata.org/generated/seaborn.heatmap.html) `annot` and `fmt` parameters.

**Comment by neongreen13** [comment]
Awesome, thank you!

**Comment by shakedzy** [comment]
Duplicate of issue #11
