### ISSUE TITLE
How to plot heatmap just for categorical and numeric features?

### ISSUE THREAD

**Issue by jijo7** [shakedzy/dython#2]
Hi Shakedzy!

Thanks a lot for sharing your nice code.

Could you please provide me with an example which shows how to plot heatmap just for categorical and numeric features? Really, I mean how it is possible to have 3 heatmap plots: 

- numeric vs numeric

- numeric vs categorical

- categorical vs categorical.

Besides, should categorical features with more than 2 category be converted into 0 or 1 using get_dummies? If there is 3 categories, is in't allowed to use 1, 2, and 3 to represent each category? 

Thank you in advance.

**Comment by shakedzy** [comment]
Hi jijo7 - 
Sure, lets' take a look at this example. Let's import libraries:
```
import pandas as pd
from dython import nominal
```
Next, let's create some test data. We'll use a `DataFrame` with four columns: Month, Day, Temperature and the length of a working day at the office. The first two are nominal (categorical), the latter two are numerical:
data = {'Month':['August','August','August','August','August','August','August','August','August','August','August','August',
 'February','February','February','February','February','February','February','February','February','February','February','February'],
'Day':['Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday',
 'Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday',],
'Temperature':[34,32,33,36,37,35,29,32,33,32,36,30,
 19,22,21,17,15,14,19,20,22,20,19,18],
'WorkingHours':[0,9.5,8.5,0,9,8.5,0,10,9.5,0,8,8.5,
 0,8.5,9,0,9,9,0,10,8,0,8.5,9.5]}
df = pd.DataFrame(data)
```
Now all you need to do is use the `associations` function, and state which columns are the nominal (categorical) ones. That's it, no additional conversions are required:
```
nominal.associations(df, nominal_columns=['Month','Day'])
```
This will yield the following heat-map:
<img width="783" alt="screen shot 2018-09-02 at 1 21 01" src="https://user-images.githubusercontent.com/15704705/44950364-87926300-ae4e-11e8-8d9c-6bffef4674c0.png">
The associations between the different features are different:
- The association between Month and Day is computed using Cramer's V (This could be replaced with Theil's U by adding `theil_u=True` to the parameters of `nominal.associations`)
- The association between Month and Temperature is computed using Correlation Ratio (same for Day and WorkingHours)
- The association between Temperature and WorkingHours is computed using Pearson's R (correlation)
Hope this clears things for you!

**Comment by jijo7** [comment]
@shakedzy Hi!

I am so grateful for sharing your time and knowledge.  

Really, I learned a lot from your code. 

Sorry, could you please let me know if is it possible to plot two separate plots for categorical features i.e.,  one for correlation ratio and another one for Cramer's V? Maybe some extra cells need to be masked each time.

Thank you in advance.
Warmest regards,

**Comment by shakedzy** [comment]
@jijo7 -
It is not possible to plot Correlation Ratio for categorical features only, as by definition Correlation Ratio is computed for a categorical feature and a numerical feature.
If you wish to plot Cramer's V for categorical features only, simply pass only the categorical columns to the function, like I posted at the bottom of my previous comment:
```
nominal.associations(df[['Month,'Day']], nominal_columns='all')
```
Where `['Month,'Day']` are the only categorical columns in `df`.

**Comment by shakedzy** [comment]
@jijo7 I cannot understand what are you trying to do.. I don't know what you have in `df` or `df3` and what is the general purpose.. Also, you don't use any of my code, so I don't understand how is this related to my library..

**Comment by jijo7** [comment]
@shakedzy Sorry, `df `or `df3 `is just provided as an example to show what we could do if we want to plot the lower triangle of the correlation matrix. 
Now, I want to know if it is possible to use such a method to plot correlation ratio and Cramer's V separately.
Surely, I want to use your library but I need Pearson's correlation, correlation ratio and Cramer's v to be separately plotted (i.e., 3 plots).
Thanks in advance.

**Comment by shakedzy** [comment]
@jijo7 As I've replied before, if you want Cramer's V separately, pass only the categorical columns. Correlation Ratio is for categorical and numerical together.
If you want to mask one of the triangles, yes you can, Cramer's V and Correlation Ratio are symmetrical (note that Thiel's U isn't).

**Comment by jijo7** [comment]
@shakedzy Could you please let me know how to plot just the following part (correlation ratio) in your example?

![image](https://user-images.githubusercontent.com/22023225/44956329-6c1f6a80-aed7-11e8-985d-44620836038d.png)
Thanks in advance.

**Comment by shakedzy** [comment]
```
assoc = nominal.associations(df, nominal_columns=['Month','Day'], plot=False, return_results=True)
sns.heatmap(assoc.loc[['Day','Month'],['Temperature','WorkingHours']], annot=True, fmt='.2f')
```

**Comment by harsh6372** [comment]
@shakedzy how can one increase the plot size using nominal

**Comment by shakedzy** [comment]
Use `figsize`. Please see the documentation at shakedzy.xyz/dython

**Comment by AkshayRShiraguppi** [comment]
I have literally copied and pasted your code and tried to run it. But, I am getting following error? @shakedzy 

data = {'Month':['August','August','August','August','August','August','August','August','August','August','August','August',
 'February','February','February','February','February','February','February','February','February','February','February','February'],
'Day':['Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday',
 'Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday','Sunday','Monday','Tuesday',],
'Temperature':[34,32,33,36,37,35,29,32,33,32,36,30,
 19,22,21,17,15,14,19,20,22,20,19,18],
'WorkingHours':[0,9.5,8.5,0,9,8.5,0,10,9.5,0,8,8.5,
 0,8.5,9,0,9,9,0,10,8,0,8.5,9.5]}

df2 = pd.DataFrame(data)

nominal.associations(df2, nominal_columns=['Month','Day'])



```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 nominal.associations(df2, nominal_columns=['Month','Day'])

File ~\Anaconda3\envs\envname\lib\site-packages\dython\nominal.py:777, in associations(dataset, nominal_columns, numerical_columns, mark_columns, nom_nom_assoc, num_num_assoc, nom_num_assoc, symmetric_nom_nom, symmetric_num_num, display_rows, display_columns, hide_rows, hide_columns, cramers_v_bias_correction, nan_strategy, nan_replace_value, ax, figsize, annot, fmt, cmap, sv_color, cbar, vmax, vmin, plot, compute_only, clustering, title, filename, multiprocessing, max_cpu_cores)
    769 mask = np.vectorize(lambda x: not bool(x))(inf_nan_mask) + np.vectorize(
    770     lambda x: not bool(x)
    771 )(sv_mask)
    772 vmin = vmin or (
    773     -1.0
    774     if len(displayed_features_set) - len(nominal_columns) >= 2
    775     else 0.0
    776 )
--> 777 ax = sns.heatmap(
    778     corr,
    779     cmap=cmap,
    780     annot=annot,
    781     fmt=fmt,
    782     center=0,
    783     vmax=vmax,
    784     vmin=vmin,
    785     square=True,
    786     mask=mask,
    787     ax=ax,
    788     cbar=cbar,
    789 )
    790 plt.title(title)
    791 if filename:

File ~\Anaconda3\envs\envname\lib\site-packages\seaborn\_decorators.py:46, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
     36     warnings.warn(
     37         "Pass the following variable{} as {}keyword arg{}: {}. "
     38         "From version 0.12, the only valid positional argument "
   (...)
     43         FutureWarning
     44     )
     45 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46 return f(**kwargs)

File ~\Anaconda3\envs\envname\lib\site-packages\seaborn\matrix.py:553, in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, xticklabels, yticklabels, mask, ax, **kwargs)
    551 if square:
    552     ax.set_aspect("equal")
--> 553 plotter.plot(ax, cbar_ax, kwargs)
    554 return ax

File ~\Anaconda3\envs\envname\lib\site-packages\seaborn\matrix.py:302, in _HeatMapper.plot(self, ax, cax, kws)
    299     kws.setdefault("vmax", self.vmax)
    301 # Draw the heatmap
--> 302 mesh = ax.pcolormesh(self.plot_data, cmap=self.cmap, **kws)
    304 # Set the axis limits
    305 ax.set(xlim=(0, self.data.shape[1]), ylim=(0, self.data.shape[0]))

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\__init__.py:1412, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1409 @functools.wraps(func)
   1410 def inner(ax, *args, data=None, **kwargs):
   1411     if data is None:
-> 1412         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1414     bound = new_sig.bind(ax, *args, **kwargs)
   1415     auto_label = (bound.arguments.get(label_namer)
   1416                   or bound.kwargs.get(label_namer))

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\axes\_axes.py:6070, in Axes.pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   6066 C = C.ravel()
   6068 kwargs.setdefault('snap', rcParams['pcolormesh.snap'])
-> 6070 collection = mcoll.QuadMesh(
   6071     coords, antialiased=antialiased, shading=shading,
   6072     array=C, cmap=cmap, norm=norm, alpha=alpha, **kwargs)
   6073 collection._scale_norm(norm, vmin, vmax)
   6074 self._pcolor_grid_deprecation_helper()

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\collections.py:2016, in QuadMesh.__init__(self, *args, **kwargs)
   2013 self._bbox.update_from_data_xy(self._coordinates.reshape(-1, 2))
   2014 # super init delayed after own init because array kwarg requires
   2015 # self._coordinates and self._shading
-> 2016 super().__init__(**kwargs)

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\collections.py:221, in Collection.__init__(self, edgecolors, facecolors, linewidths, linestyles, capstyle, joinstyle, antialiaseds, offsets, transOffset, norm, cmap, pickradius, hatch, urls, zorder, **kwargs)
    218 self._transOffset = transOffset
    220 self._path_effects = None
--> 221 self.update(kwargs)
    222 self._paths = None

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\artist.py:1066, in Artist.update(self, props)
   1063             if not callable(func):
   1064                 raise AttributeError(f"{type(self).__name__!r} object "
   1065                                      f"has no property {k!r}")
-> 1066             ret.append(func(v))
   1067 if ret:
   1068     self.pchanged()

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\collections.py:2077, in QuadMesh.set_array(self, A)
   2072     if faulty_data:
   2073         raise TypeError(
   2074             f"Dimensions of A {A.shape} are incompatible with "
   2075             f"X ({width}) and/or Y ({height})")
-> 2077 return super().set_array(A)

File ~\Anaconda3\envs\envname\lib\site-packages\matplotlib\cm.py:477, in ScalarMappable.set_array(self, A)
    475 A = cbook.safe_masked_invalid(A, copy=True)
    476 if not np.can_cast(A.dtype, float, "same_kind"):
--> 477     raise TypeError(f"Image data of dtype {A.dtype} cannot be "
    478                     "converted to float")
    480 self._A = A

TypeError: Image data of dtype object cannot be converted to float
```
