### ISSUE TITLE
How can I change the size of the heat map?

### ISSUE THREAD

**Issue by siserte** [shakedzy/dython#20]
I have a heat map with many attributes generated with:

`associations(dfVasp,nominal_columns=['user',` 'partition_name', 'qos', 'account'], theil_u=True)

But the values are cropped since there is no more space for them.

**Comment by siserte** [comment]
As easy as adding to the function the argument:  figsize=(16,9)

**Comment by shakedzy** [comment]
You can also change the precision of the numbers. Try adding `fmt=.1f` to have only one figure after the floating point.

**Comment by shakedzy** [comment]
Duplicate of issue #11
