### ISSUE TITLE
conditional_entropy fonction 

### ISSUE THREAD

**Issue by iamadouhassane** [shakedzy/dython#21]
Hello Shaked Zychlinski,

Thanks your for work . Excellent article !
Can you please complet your fonction code of theils_u  excatly on conditional_entropy  and 
correlation_ratio .

Thanks.

**Comment by shakedzy** [comment]
What do you mean by completing the functions?

**Comment by iamadouhassane** [comment]
def theils_u(x, y):
    s_xy = conditional_entropy(x,y)
    x_counter = Counter(x)
    total_occurrences = sum(x_counter.values())
    p_x = list(map(lambda n: n/total_occurrences, x_counter.values()))
    s_x = ss.entropy(p_x)
    if s_x == 0:
        return 1
    else:
        return (s_x - s_xy) / s_x

In which library can I call conditional_entropy? 
I work in python3.7 

Thanks

**Comment by iamadouhassane** [comment]
I use pycm finaly  in python3.7  

from pycm import *
def theils_u(x, y):
    x_counter = Counter(x)
    x = list(x) ## actual_vector 
    y = list(y) ## predict_vector
    cm = ConfusionMatrix(x, y,digit=5)
    total_occurrences = sum(list(x_counter.values()))
    p_x = list(map(lambda n: n/total_occurrences, x_counter.values()))
    s_x_log = sum(-log(p_x)*p_x)
    s_x = ss.entropy(p_x)
    I_xy = cm.overall_stat['Mutual Information']
    if s_x == 0:
        return 1
    else:
        return (I_xy / s_x)

**Comment by shakedzy** [comment]
`conditional_entropy` is a function of this library.. You copy-pasted `theils_u` from my blogpost, whee it explicitly says (right above the function you copied): 

> full code with the conditional_entropy function can be found on my Github page

Read this library's documentation, or simply install it.

**Comment by iamadouhassane** [comment]
thanks Shaked , I read complet documentation.
