### ISSUE TITLE
calculation of cramer v

### ISSUE THREAD

**Issue by tqx94** [shakedzy/dython#22]
Hi, would like to know why you included the calculation of  the following for cramer v?

```
phi2corr = max(0, phi2-((k-1)*(r-1))/(n-1))
    rcorr = r-((r-1)**2)/(n-1)
    kcorr = k-((k-1)**2)/(n-1)

```
When wiki stated this formula:
`phi2/min(k-1,r-1) 
`

![image](https://user-images.githubusercontent.com/19548371/66711789-38df2880-edc5-11e9-9e10-a35a2d1f8db9.png)

**Comment by shakedzy** [comment]
Hi @tqx94 , please continue to scroll down on that Wikipedia page, as a few lines below what you copied you'll find exactly what I'm using (under Bias Correction). There's also an explanation to why this is used, along with a reference to the paper (which can also be found on the second line of `cramers_v` docstring).
