### ISSUE TITLE
Using natural logarithm instead of base 2

### ISSUE THREAD

**Issue by ahmedsalhin** [shakedzy/dython#35]
I wonder of the reason to use natural log in calculating the [Conditional Entropy (CE)](https://github.com/shakedzy/dython/blob/44ead00d4a7fcf8ac4677ab34b6b2aa772256e33/dython/nominal.py#L68) instead of base 2. 

May be it is more logical "not" to scale the CE to bits (log2) when calculating the correlation between categorical variables, but would appreciate more clarification.

**Comment by shakedzy** [comment]
Hey @ahmedsalhin - this is a very good question. I guess I used natural log as I come from the field of physics, and therefore it feels more natural to me (hehe). Also, it is how [regular entropy](https://en.wikipedia.org/wiki/Entropy) is defined. Still, as we're discussing here information-theory, I guess using base 2 would make more sense. I guess it will be smart to add an option to change the base.

**Comment by ahmedsalhin** [comment]
@shakedzy thanks for prompt reply. I can add the option to use base 2 in a PR if you are fine with it?

**Comment by shakedzy** [comment]
Sounds awesome!

**Comment by shakedzy** [comment]
Come to think of it, I think it will be more general to allow _any_ base, not just _e_ and 2.
