### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hhnguyen7** [shakedzy/dython#4]
Hi,
I installed the dython module as per your instructions. But then I could not import nominal or the other function. I get an error saying that they are not found in dython. Could you please help?
Thank you.

**Comment by shakedzy** [comment]
Seems like you didn't install things correctly. Please specify exactly what you did and how you import the library

**Comment by hhnguyen7** [comment]
I did the following:
1. git clone https://github.com/shakedzy/dython.git
2. cd dython
3. pip install -e .
4. from dython import nominal
5. I get the error cannot import the name 'nominal'

Thank you.

**Comment by shakedzy** [comment]
Can you post screenshots of how you install and import?

**Comment by hhnguyen7** [comment]
I reinstalled the package, and now it works. I don't know what I did differently other than:
1. pip install . instead of pip install -e .
2. disconnecting and reconnecting to anaconda jupyter notebook.
Sorry for the issue non-issue. Thanks for your help!
