### ISSUE TITLE
Module import not possible?

### ISSUE THREAD

**Issue by Createdd** [shakedzy/dython#41]
### Version check:

sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
0.4.6

### Describe the bug:

Code to reproduce:
```python
import dython as dy

dy.nominal.associations(...)
```

## Error message:

Error message:
```
AttributeError: module 'dython' has no attribute 'nominal'
```

**Comment by shakedzy** [comment]
This is not how Python works. Try:
```python
from dython.nominal import associations
```

**Comment by shakedzy** [comment]
Hey @Createdd ,so I was thinking about this last night - there is a way to make this happen. I'll add it to the next version. Thanks for the idea!

**Comment by Createdd** [comment]
Yes! Thanks a lot! Love your articles and work btw :)

**Comment by shakedzy** [comment]
thanks :)
