### ISSUE TITLE
Update documentation to return results in associations.

### ISSUE THREAD

**Issue by Createdd** [shakedzy/dython#46]
In your docstring for `cluster_correlations ` you have the following example:
```python
 Example:
    --------
    >> correlations = associations(
        customers,
        return_results=True,
        plot=False
    )
    >> correlations, _ = cluster_corre
```

Key element here is ` return_results=True,`.
That is the only place I found this parameter. In fact, so far, I could only get the correlations when this flag is set to true. If I don't set it, somehow the function does not return anything. But rather NoneType. Not quite sure if this is a bug. But I think the `return_results` parameter should be in the documentation. 

Or have I misunderstood something?

kind regards,

**Comment by shakedzy** [comment]
Hi @Createdd, I'm not sure I understand.. any chance you can paste an example?

**Comment by shakedzy** [comment]
I understand what you're saying.. true, the docstring is not updated, I'll fix it. Thanks!

**Comment by Createdd** [comment]
Hi @shakedzy , 

somehow the associations function does not return the results described in the documentation. Only when I set the argument `return_results` to True. It is illustrated in your example from the 'cluster_correlations' function. Without setting the argument to True it does return None, and therefore it is not useable when plotting is set to False. 

![image](https://user-images.githubusercontent.com/22077628/80079059-0ff7d700-8550-11ea-9f39-e869b1990eb8.png)

The variable inspector shows this as well: 
![image](https://user-images.githubusercontent.com/22077628/80079114-230aa700-8550-11ea-82ca-be354055481d.png)



Do you know what I mean?

**Comment by shakedzy** [comment]
Hi, of course it doesn't return anything when `return_results=False`.. Results are only returned when `return_results=True`.. Same for `plot`.
Anyway, starting from v0.5.0, this function always returns results by default.

**Comment by Createdd** [comment]
Yes! That was my point :)  Because it was not described in the documentation: 
![image](https://user-images.githubusercontent.com/22077628/80080327-c27c6980-8551-11ea-91f4-745143212d0e.png)

Thanks for the fast response and for the update :)

**Comment by shakedzy** [comment]
Documentation is up to date with the latest version. Update your version too.
