### ISSUE TITLE
Optional parameter: cbar for associations

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [shakedzy/dython#48]
### Describe the new feature:
It would be nice to have the option to disable the cbar for the associations plot. I know associations already has a ton of parameters, so I'm thinking of how to fix this neatly, but so far I do not have a solution. 

### What is the current outcome? 
Currently, the cbar is enabled and cannot be disabled anymore. This was possible by passing it in the kwargs, but with the explicit parameters, this is not longer possible. 

### Is it backward-compatible? 
Yes, if default is True, nothing should change for older versions. 

Nice template btw :)

**Comment by shakedzy** [comment]
Cool, if you'd like to merge your PR it would be awesome :)

**Comment by Baukebrenninkmeijer** [comment]
Since you already added it, i'm closing it.
