### ISSUE TITLE
Distinguish plot and show for associations parameters

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [shakedzy/dython#49]
This is more of a suggestion, since I find myself working around it.

### Describe the new feature:
Have the option to show the plot (currently done with the `plot` parameter), but also the option to plot (currently no option). The function `associations` is very neat, but you don't always want to plot the results, but just get the dataframe. I suggest adding a `show` parameter.

### What is the current outcome? 
Currently, there is no way not to plot (i.e. create matplotlib object). This means, when working in a notebook, it will always show the plot at the end of a cell, disregarding the value of the `plot` parameter. 

### Is it backward-compatible? 
No. `show` would replace `plot` in functionality, and `plot` would get a different meaning. 

My current workaround is to create a figure/ax before calling associations, and passing `ax` to associations. Then I call `plt.close(ax)` to remove the plot.

**Comment by Baukebrenninkmeijer** [comment]
Btw, if you this or #48 are cool, I can also create a pull request. Let me know what you think.

**Comment by shakedzy** [comment]
Hey @Baukebrenninkmeijer - isn't this already solved in version 0.5.0? The output is now a dict, with the dataframe and plot.
If you only want the dataframe, you can simply do:
```
df = associations(data, plot=False, ...)['corr']
```

**Comment by Baukebrenninkmeijer** [comment]
Yes, but the plot doesn't need to be returned unfortunately. The plot is still in the global matplotlib statespace, and thus will be rendered. At least, that was my experience today.

**Comment by Baukebrenninkmeijer** [comment]
I'll see if I can get an example tomorrow.

**Comment by shakedzy** [comment]
I think I understand what you're saying

**Comment by Baukebrenninkmeijer** [comment]
As you can see below, I have set `plot=False`, but the figure is still rendered. As soon as you instantiate a matplotlib figure, it will show at the end of a cell.

![image](https://user-images.githubusercontent.com/9077462/81279589-a0a5db00-9057-11ea-8cc9-8ced5fc90327.png)

It can be fixed fairly simple by setting a parameter that determines whether it will even create a plot, like I suggested above. It would be nice to do it in a backward compatible mode, but that might be a bit confusing if `plot` keeps referring to showing the plot.

**Comment by shakedzy** [comment]
Check this PR: https://github.com/shakedzy/dython/pull/50
Is this what you asked for?

**Comment by Baukebrenninkmeijer** [comment]
Yes, great work! Also really like the solution :).
