### ISSUE TITLE
Correlation ratio in nominal.py class

### ISSUE THREAD

**Issue by Jean-0101** [shakedzy/dython#51]
Hello and thank you for this useful package. I have been calculating the correlation with nominal.py class. I have a non-linear numeric data and categorical data. I was wondering which statistical method are you using when you calculate correlation ratio with non-linear numeric and categorical data?

**Comment by shakedzy** [comment]
Correlation ratio is defined in the same way regardless if the data is linear or not. You can see the definition here: https://en.wikipedia.org/wiki/Correlation_ratio

**Comment by Jean-0101** [comment]
I see thank you. Have a good day.
