### ISSUE TITLE
nan_strategy as 'drop_samples'

### ISSUE THREAD

**Issue by uy4567** [shakedzy/dython#52]
Hi,

Thanks for this amazing package. I am trying it over a dataset of 1220*500. I have categorized the columns in 3 types: Continuous, Ordinal and Nominal. There are missing values in the dataset, which I don't wish to impute with anything and makes sense to use 'drop_samples' for the nan_strategy parameter. However, when I run the associations() method on the dataset, I get below error. 

ValueError: zero-size array to reduction operation maximum which has no identity

Can you please suggest a way to solve this? Also, does it make sense to use this method when I have ordinal variables as well because in that case we use 'spearman rank correlation'.

Thanks in advance!

**Comment by shakedzy** [comment]
Hi, there's too much missing information here. Please open an error report here: https://github.com/shakedzy/dython/issues/new/choose and follow the instructions so I can assist.
