### ISSUE TITLE
nan_strategy as "drop_samples"

### ISSUE THREAD

**Issue by uy4567** [shakedzy/dython#53]
### Version check:

Run and copy the output:
```python
import sys, dython
print(sys.version_info)
print(dython.__version__)
```
0.5.1
### Describe the bug:

Code to reproduce:
```python
import dython
# your code goes here
```
data = pd.read_excel("\\data.xlsx")
[dython_test.xlsx](https://github.com/shakedzy/dython/files/4629077/dython_test.xlsx)

nominal_var = ['a4a','k17','cnd2','k16','bmj5']
dython_corr = associations(data,nominal_columns=nominal_var,plot=False,nan_strategy ='drop_samples')

## Error message:

Error message:
```
# your error message
```
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation maximum which has no identity
## Input data:

[dython_test.xlsx](https://github.com/shakedzy/dython/files/4629074/dython_test.xlsx)

**Comment by shakedzy** [comment]
You use `drop_samples` but there's not even a single sample in your data without a missing value, so all your data is dropped:
```python
>>> data.dropna(axis=0)
Empty DataFrame
Columns: [a6a, a4a, k17, cnd2, k15a, j2, k16, j6, j7a, j7b, l1, l2, bmj5, k5f1]
Index: []
```
Which is exactly what the error you get says: `ValueError: zero-size array ...`. Either change the data, or use a different `nan_strategy`.
