### ISSUE TITLE
associations un-needed steps when plot=False

### ISSUE THREAD

**Issue by johntmyers** [shakedzy/dython#55]
Hi, this library is amazing! I've noticed that when doing certain actions, un-necessary matplotlib steps are executed. One example would be when using the `associations()` function. I patched my installed version to test, but made these changes so that if `plot=False` we don't worry about doing any of the steps needed to plot.

```python
    corr, columns, nominal_columns, inf_nan, single_value_columns = _comp_assoc(dataset, nominal_columns, mark_columns,
                                                                                theil_u, clustering, bias_correction,
                                                                                nan_strategy, nan_replace_value)
    if not plot:
        ax = None
    if ax is None and plot:
        plt.figure(figsize=figsize)
    if inf_nan.any(axis=None):
        inf_nan_mask = np.vectorize(lambda x: not bool(x))(inf_nan.values)
        if plot:
            ax = sns.heatmap(inf_nan_mask,
                            cmap=['white'],
                            annot=inf_nan if annot else None,
                            fmt='',
                            center=0,
                            square=True,
                            ax=ax,
                            mask=inf_nan_mask,
                            cbar=False)
    else:
        inf_nan_mask = np.ones_like(corr)
    if len(single_value_columns) > 0:
        sv = pd.DataFrame(data=np.zeros_like(corr),
                          columns=columns,
                          index=columns)
        for c in single_value_columns:
            sv.loc[:, c] = ' '
            sv.loc[c, :] = ' '
            sv.loc[c, c] = 'SV'
        sv_mask = np.vectorize(lambda x: not bool(x))(sv.values)
        if plot:
            ax = sns.heatmap(sv_mask,
                            cmap=[sv_color],
                            annot=sv if annot else None,
                            fmt='',
                            center=0,
                            square=True,
                            ax=ax,
                            mask=sv_mask,
                            cbar=False)
    else:
        sv_mask = np.ones_like(corr)
    mask = np.vectorize(lambda x: not bool(x))(inf_nan_mask) + np.vectorize(lambda x: not bool(x))(sv_mask)
    if plot:
        ax = sns.heatmap(corr,
                        cmap=cmap,
                        annot=annot,
                        fmt=fmt,
                        center=0,
                        vmax=1.0,
                        vmin=-1.0 if len(columns) - len(nominal_columns) >= 2 else 0.0,
                        square=True,
                        mask=mask,
                        ax=ax,
                        cbar=cbar)
    if plot:
        plt.show()
    
    return {'corr': corr,
            'ax': ax}
```

**Comment by shakedzy** [comment]
Hey @johntmyers - thanks for the feedback! The truth is that those unneeded steps are actually intended - this function always creates the matplotlib `ax` and returns it as part of the output. The `plot` flag was intended to turn off the `plt.show()` part, meaning - to simply not display it at the moment. This is useful when you want to edit the `ax`, or simply display it later. Do you think it is necessary to turn off the entire matplotlib code? If so, what will be the output?

**Comment by johntmyers** [comment]
Understood. Of course I'm speaking selfishly, but I was only interested in the actual correlations, but setting the plot param to `False` still launched the extra python processes under the hood to get ready to plot. From an interface perspective it is just a little surprising since the behavior is a little non-atomic.

If someone, like me, was using this purely to calculate some data on a backend system, with no intention to graph it, there could be undesired consequences w/ the implicit graphing logic.

In these situations I usually find it more helpful to have explicit interfaces:

- One function returns the actual correlation data

- Optionally you could pass that correlation data to another helper function whose only job it is is to create the `ax` and plot the graph

**Comment by shakedzy** [comment]
Hi @johntmyers - if you only want the DataFrame, this option already exists: use `compute_associations`. Here's the [documentation](http://shakedzy.xyz/dython/modules/nominal/#compute_associations).

**Comment by johntmyers** [comment]
Ah, great, thank you. Also, FWIW the function signature and docstrings have the `Plot` kwarg but the function does not.

**Comment by shakedzy** [comment]
Fixed it now. Thanks!
