### ISSUE TITLE
Empty values and usability for feature selection

### ISSUE THREAD

**Issue by ricklen** [shakedzy/dython#6]
Hi Shaked,

I replied on your Medium article with a question about NaN values in a column, and I partially figured out how your functions deal with NaN values. Using 'cramers_v', calling pd.crosstab(x,y) drops all rows in the dataframe which contain a NaN value. Replacing NaN with for example the string 'empty' results in different values. Haven't figured out if theils_u does the same, maybe you know about it?

Also I want to use both Cramers V and Theils U for feature selection in my machine learning project, do you have some scientific papers about feature selection referring to both Cramers V and Theils U? I have a lot of features in my dataset and I'm thinking about removing features wich have a high correlation with an other feature, what do you think about this? I'm also using Chi Square to find out whether features are correlated or not.

Hope you can help me forward.

Rick

**Comment by shakedzy** [comment]
Hi Rick,
Thanks for opening an issue on this matter - it's true that NaN values were not something I considered when implementing these functions, and so I cannot vouch for any specific behavior in this case.
I guess that before we start coding, we need to think what is the proper behavior we expect to get when using incomplete data. For example, I don't see how Conditional Entropy can be calculated for incomplete data, and as Theil's U is based on it, that probably won't work either.
I guess the way I see it is that it is possible to add a flag which will either remove line/rows with incomplete data or fill them with a special value, like "EMPTY".
Let me know what you think.

**Comment by ricklen** [comment]
I will try filling NaN values with "Empty" and compare some results, will post an update on this. Thanks!

**Comment by shakedzy** [comment]
Closing this issue in the meantime
