### ISSUE TITLE
Searching for Categorical Correlation

### ISSUE THREAD

**Issue by baajanaku** [shakedzy/dython#60]
Hi, thank you for the good job you are doing by imparting knowledge to others. I read your blog on searching for categorical correlation, and I found this code:
def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x,y)
    chi2 = ss.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2/n
    r,k = confusion_matrix.shape
    phi2corr = max(0, phi2-((k-1)*(r-1))/(n-1))
    rcorr = r-((r-1)**2)/(n-1)
    kcorr = k-((k-1)**2)/(n-1)
    return np.sqrt(phi2corr/min((kcorr-1),(rcorr-1)))

However, I was wondering how you applied it to your Mushrooms datasets since we have so many variables there.

Please, I would appreciate it if you could help me with this. I have a related problem to solve with my dataset.

Thank you

**Comment by shakedzy** [comment]
Hi @baajanaku - I used the `associations` method found in this library to handle multiple variables. Check out an example [here](http://shakedzy.xyz/dython/getting_started/examples/#associations_mushrooms_example). Also, you can check the original [Kaggle kernel](https://www.kaggle.com/shakedzy/alone-in-the-woods-using-theil-s-u-for-survival) I made. Hope this helps.
