### ISSUE TITLE
nan_strategy=_SKIP producing negative values in some cases

### ISSUE THREAD

**Issue by xavisilver** [shakedzy/dython#61]
Hello shakedzy, 
First of all, thank you for the great contribution to Python with this fantastic package. 
Also, congratulations to the paper written in TowardsDataScience.com .

I just had one question/concern after using your package.
Doing the correlation of category-category with Theil's U, I was getting negative results for some cases.
After analyzing your code, I have seen that what is causing these negative results is the parameter "nan_strategy=_SKIP"  in the function "_comp_assoc"(lines 409 and 415 in dython/dython/nominal.py).  
I do not know if this should be like this or if it is an error since you can specify the nan_strategy in parameters,

Thank you very much,
Regards,
Xavi

**Comment by shakedzy** [comment]
Hi @xavisilver - thanks for the feedback. Please be sure to go over [this closed issue](https://github.com/shakedzy/dython/issues/56) which sounds very similar to what you raised.
If this isn't the case, it's impossible to assist without data sample and the exact code you're running, so please make sure to attach these.

**Comment by xavisilver** [comment]
Hey shakedzy, 
Thanks for the answer. I have checked the issue and it is applicable to my case. I had not specified the correct format to the columns and it was reading them as numeric.
Thank you,
Xavi,
