### ISSUE TITLE
plt.subplot eopt markers are plotted in wrong axis

### ISSUE THREAD

**Issue by matthiaswalle-eth** [shakedzy/dython#64]
### Version check:

Run and copy the output:
Python 3.8.6 (default, Sep 25 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, dython
>>> print(sys.version_info)
sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
>>> print(dython.__version__)
0.6.1
>>> 

### Describe the bug:

Code to reproduce:
```python
import dython
fig, axs = plt.subplots(ncols=2, nrows=2,figsize=(fig_height,sub_fig_width))
results = roc_graph(y_test, y_pred, class_names=class_names**,ax=axs[0,1],eopt=True**,plot=True,colors=p)
```

## Error message:
[ WARNING ] - No handles with labels found to put in legend.

Error message:
# your error message
eopt is plotted in last subplot (axs[1.1])
No legend is plotted

**Comment by shakedzy** [comment]
Hi, can you please supply the data you use? what are `y_test`, `y_pred`, 'class_names` and `p`?

Also, what do you set `eopt` as `True**`? `True` is not a `dict`. Same for `class_names` - it's suppose to be a `list`, not a `dict`..
