### ISSUE TITLE
Can I get a tutorial on how the library works?

### ISSUE THREAD

**Issue by cwai2007** [shakedzy/dython#65]
I loved your article on correlation:  https://towardsdatascience.com/the-search-for-categorical-correlation-a1cf7f1888c9

I know you published the library, but since I am still new, I would love to see the code you used in the article, so I have some working examples of how the library is supposed to work.

**Comment by shakedzy** [comment]
Hi, you have examples of some functions in the documentation: https://shakedzy.xyz/dython/getting_started/examples/
