### ISSUE TITLE
Specifying the range of correlation displayed on the legend and in the heatmap

### ISSUE THREAD

**Issue by pierreolivierbonin** [shakedzy/dython#68]
### Describe the new feature:
For some datasets, all of the observed correlations are positive. It would make things easier to visualize if we were able to specify the correlation range directly through dython. For example, I would like to specify a range of 0 to 1 instead of -1 to 1.

### What is the current outcome? 
For now, unless I am mistaken, there is a vmin and vmax option in Seaborn's heatmap, but this option does not work directly in dython.

### Is it backward-compatible? 
I believe it would probably be, but since I have no experience as a Python library developer, I can't confirm.

**Comment by shakedzy** [comment]
Hi @pierreolivierbonin , that actually already happens automatically for you, see line [587 in nominal.py](https://github.com/shakedzy/dython/blob/6269485dd6c90240dc14f8eb10851c0a913932cc/dython/nominal.py#L587). It basically sets `vmin` to be -1 if there is any use of Pearson's R, and if not it is set to 0.

**Comment by pierreolivierbonin** [comment]
Hi @shakedzy. Sorry if I'm using Github incorrectly or something, I'm very new to all of this. I understand from your reply that you prefer not to allow the user of dython to specify their own vmax and vmin range, then? If I really insisted on doing that, I suppose I would have to go back to Seaborn? Or to tweak my own version of line 587 in nominal.py?

**Comment by shakedzy** [comment]
Hi @pierreolivierbonin , could you please provide an example of a heatmap where changing the range is required?

**Comment by pierreolivierbonin** [comment]
Thanks for the follow-up, @shakedzy . An example would be a case where your dataset produces positive correlations only (not a single negative correlation). It happened to me a few times already. In those cases, dython's heatmap is not optimal because it means that half of the colors mapped onto the grid are left unused. In other words, all of the colors matching the [-1 to 0] range are unused. Hence it would be more optimal to have the option to select the [0 to 1] range only – or whatever range fits your dataset, really –  because the color range would more appropriately reflect the nuances of the variation across correlation ratios and correlation coefficients.

**Comment by shakedzy** [comment]
I see. OK, I think I can add this, shouldn't be too complex.

**Comment by shakedzy** [comment]
merged changes, now available as of version 0.6.2
