### ISSUE TITLE
Running dython.nominal associations twice in same jupyter notebook environment

### ISSUE THREAD

**Issue by myrthewouters** [shakedzy/dython#73]
Hi, 

dython version: 0.6.2

Thank you for your work! I'm experiencing some issues when running the dython.nominal associations function twice in the same jupyter notebook environment. 

For the sake of reproducability, I used the Adult dataset (https://www.kaggle.com/wenruliu/adult-income-dataset).
```
df = pd.read_csv('adult.csv')
```

```
associations(df.copy());
```

```
associations(df.copy());
```

When running this code twice, the second association matrix contains a nan value, where the first doesn't (see image below). I am not sure if this is a dython issue, or a scipy issue in general. Do you have any thoughts on this, or how to solve this issue?
![image](https://user-images.githubusercontent.com/47980383/105846900-23533980-5fdd-11eb-8631-89a591e3a484.png)

**Comment by shakedzy** [comment]
Hey @myrthewouters - I ran the same code on my laptop and everything works as it should.. can you try to run my notebook and see if the issue remains?
[Untitled9.ipynb.zip](https://github.com/shakedzy/dython/files/5875549/Untitled9.ipynb.zip)

**Comment by myrthewouters** [comment]
@shakedzy thanks for your quick response! I tried running your notebook (both in my existing environment and also in a new conda environment with only dython installed), and the issue remains..

What versions of the packages are you using (I suggest scipy might be causing the problem)? Or could there be another problem?

**Comment by myrthewouters** [comment]
@shakedzy update: I had scipy 1.6.0 (latest release) on my machine. I now downgraded to scipy 1.2.1 and the issue is resolved.

**Comment by shakedzy** [comment]
super weird. I use `scipy==1.5.2`.. I'll try upgrading and see if I get the same issue

**Comment by myrthewouters** [comment]
Weird.. I just tried `scipy==1.5.2` and I'm getting the issue again. The only version I've tried that does not give me the issue is `scipy==1.2.1`.

**Comment by shakedzy** [comment]
Closing this for now, @myrthewouters please let me know if the issue persists or was solved!
