### ISSUE TITLE
Please confirm the conditional entropy equation

### ISSUE THREAD

**Issue by linsalrob** [shakedzy/dython#77]
I think your conditional entropy equation in [line 86](https://github.com/shakedzy/dython/blob/f9dde9e40dfbaaf3aca6fce085b2d1fcefa0a345/dython/nominal.py#L86) of `nominal.py` is inverted:

```
        entropy += p_xy * math.log(p_y / p_xy, log_base)
```

I believe that the equation should be:

```
        entropy += -1 * p_xy * math.log(p_xy / p_y, log_base)
```

[This Wikipedia page](https://en.wikipedia.org/wiki/Conditional_entropy) has the equation as `p(x,y) / p(x)` but _note:_ their equation is `S(Y|X)` while yours is `S(X|Y)`.

In addition, with your equation,  the numbers are positive (because `p_y / p_xy > 1`, since `p_y` > `p_xy`) but should be negative (hence the -1).

Can you please take another look and confirm the equation in case I misunderstood?

**Comment by shakedzy** [comment]
The formula is correct, as `log(x/y) = -log(y/x)`
