### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by roccojhu** [shakedzy/dython#8]
Hi guys,

First of all, thanks a lot for the amazing work here. As a stats and 'metrics-trained data scientist who is working in Python now, this is a godsend.

I was using your theil's U and cramer's V functions, but made my own function to plot results for a variable number of inputs and for both functions.

How can I contribute this to the code base?

**Comment by shakedzy** [comment]
Hi there! No guys here, just a single person :) I'm happy you find this useful - I haven't really thought of any organized contribution methods, I guess you can create a pull request, and let's talk about it :) I really appreciate this, thanks!
