### ISSUE TITLE
Question regarding the correlation rotio code for continuous and categorical variables

### ISSUE THREAD

**Issue by tamasbarat** [shakedzy/dython#88]
Hey Shaked, 

I am currently working on my thesis for which I aim to predict the routes of NFL pass receivers. Basically, I am dealing with a typical classification problem. As I have continuous and categorical features in my training data, I would really like to use the code you provided for this case as it would help me investigate the potential predictive power of features in regards to my target variable 'route'. However, I am struggling to get the code running with my data. I am new to Python and find it difficult to see where I need to define objects or plug in the specifics of my dataset into your code. Essentially, all I am asking for is an indication of what I need to plug in where. Sorry for this micro-management-like question, but I could not help myself.

Here is my dataframe, to give you an idea what I am dealing with.
![image](https://user-images.githubusercontent.com/80772765/125443152-646ce595-754e-4cdb-a266-a17d164c82ff.png)

Your help would be much appreciated!

**Comment by shakedzy** [comment]
Hey @tamasbarat , I don't believe I understand what you ask for - but to get the associations between all features, all you need to do is:
```python
from dython.nominal import associations
associations(df)
``` 
Is that what you asked?

**Comment by tamasbarat** [comment]
Hey @shakedzy! Thanks for fast reply! Just to clarify, I saw your code for a correlation matrix including categorical and numeric variables on towardsdatascience.com. Here a picture of the code I am talking about: 
![image](https://user-images.githubusercontent.com/80772765/125764521-6486af30-55f0-4ce3-94ed-a65223671525.png)
As my dataframe consists of numeric and categorical variables I wanted to apply it but I had trouble getting it running.  Likewise, I tried to implement the code you sent in your previous message but I get the error code 
`ModuleNotFoundError: No module named 'dython'`.  I am using Python 3.

**Comment by shakedzy** [comment]
It seems like you haven't installed the package.. please follow the documentation on shakedzy.xyz/dython, and especially the installation section.

**Comment by tamasbarat** [comment]
Oh my bad, I have fixed that error now. Thank you for your help!

**Comment by tamasbarat** [comment]
However, now I get a new error I cannot get my head wrapped around. 
![image](https://user-images.githubusercontent.com/80772765/127129107-9edde252-6c75-428a-a90e-673736d4d475.png)

Looking up the error on StackOverflow, most cases describe that this error pops up when a new category is added to an existing categorical variable without defining the new category beforehand. I checked for all my categorical variables the unique values and categories to be sure my error does not relate to the cases on StackOverflow. I also ensured that the features in my dataset have the data types float, integer, and category. Now I am asking myself if there is any other reason why I get this error and how I can solve it?

**Comment by shakedzy** [comment]
what are the columns names of your `df`?

**Comment by tamasbarat** [comment]
Hey, so these are the names of my data frame's columns
![image](https://user-images.githubusercontent.com/80772765/127768868-5d30a120-1235-409a-8ab5-b26ae69a1961.png)

**Comment by tamasbarat** [comment]
Hey. so these are the names of my data frame's columns 
![image](https://user-images.githubusercontent.com/80772765/127768905-e0877173-1669-4661-9153-a42ce301ca64.png)

**Comment by shakedzy** [comment]
Please run `df.info()` and paste the output

**Comment by tamasbarat** [comment]
![image](https://user-images.githubusercontent.com/80772765/128061028-84ce50a2-0f12-4388-a1f1-519b1efc77b3.png)
 This is the complete `df`, however, I only want to use `associations` on the columns specified in the previous screenshot.

**Comment by shakedzy** [comment]
I think the issue here is that you use both the `numerical_columns` and the `nominal_columns` options. Quoting the [documentation](http://shakedzy.xyz/dython/modules/nominal/#associations):

> **`nominal_columns`**: Only used if `numerical_columns` is `None`.

you can only use one of these, not both. What you actually want to do is simply:
```
associations(df[ ... ])
```
where `...` are the list of columns you want to plot for. The auto column-detection should work in your case. If it doesn't, only then you need to use either `nominal_columns` or ` numerical_columns`

**Comment by tamasbarat** [comment]
Hey Shaked, everything works now, thanks for your great support! I have a final question about the graphical representation of the correlation matrix. Due to the great number of variables, my matrix looks currently like this:  
![image](https://user-images.githubusercontent.com/80772765/129104569-9bf31098-a796-477d-9675-fddf377bcf71.png)
 Is there a possibility to adjust the matrix size manually so that all variables fit on the matrix and the numbers are readable? If not I will just use values from the subplot.

**Comment by shakedzy** [comment]
Yes, `figsize`. Read the documentation.
