### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [shakedzy/dython#90]
### Describe the new feature:

It would be great to have a conda recipe so that it can be included with projects that have more complicated build processes (for example, using libraries that need C/C++ compilers).

### What is the current outcome? 

Have a recipe for `dython` on the conda-forge channel.

### Is it backward-compatible? 

Yes, and it would be forward-compatible as well, because the conda bots can automatically fetch new sdists pushed to pypi.

**Comment by sarthakpati** [comment]
I am already working on this: https://github.com/conda-forge/staged-recipes/pull/15632

Happy to add anyone needed as a maintainer.

**Comment by shakedzy** [comment]
Hey @sarthakpati ! That's an excellent idea. As I don't use Conda, I doubt if I can assist here - but seems like you're on it yourself :) let me know if there's anything specific I can assist with.

**Comment by sarthakpati** [comment]
I am happy to take this on. #91 would be the first step towards this. 😄

**Comment by shakedzy** [comment]
Hey @sarthakpati ! Seems like everything is set up - great work! thanks :) As I'm not using Conda, and less aware of how it works, I'll ask you - when a new version is released, what needs to be done in order to push it to Conda? At the moment I'm using Github Actions to automatically deploy any new version of Dython directly to PyPI. What do I need to add?

**Comment by sarthakpati** [comment]
You don't need to do anything. Conda bots pick up the new version from pip and put the PR by themselves. 😄

**Comment by shakedzy** [comment]
Amazing work. Thanks!

**Comment by shakedzy** [comment]
I'm away from my laptop, and I'd like to add the new conda installation instructions to the website too. As this requires a mkdocs build, I'll be able to merge this PR only next week.. Thanks again, awesome work!

**Comment by shakedzy** [comment]
Done! @sarthakpati , thanks a lot - your name now appears on the Change-Log :)

**Comment by shakedzy** [comment]
@sarthakpati it seems the new versions are not noticed by Conda.. any idea?

**Comment by shakedzy** [comment]
My bad, it does. The Conda badge doesn't display the _post2_ suffix for some reason..
