### ISSUE TITLE
Option to choose which columns/rows to display in associations heatmap

### ISSUE THREAD

**Issue by jayceslesar** [shakedzy/dython#92]
### Correlation matrix with option to hide half of it
Would be cool to have a really nice pre-packaged set of analysis tools in python, previously I do a lot of this EDA in R, but will fit far better into workflows if I can just reproduce the same EDA in python...(I have a few other ideas but this is a quick add I would think)

I propose adding an option to hide either the top or bottom of the plot that is outputted on top 

### What is the current outcome? 
Not sure what to say here...
I think a quick implementation of this [searborn example](https://seaborn.pydata.org/examples/many_pairwise_correlations.html) somewhere around [here](https://github.com/shakedzy/dython/blob/master/dython/nominal.py#L667) in `nominal.py` is a possible solution.

### Is it backward-compatible? 
Should be backward compatible, just changes the look of the plot to remove clutter.

**Comment by shakedzy** [comment]
Hey @jayceslesar ! The idea of plotting only specific rows or columns is awesome, and is actually something that's been on my mind for quite some time now, but didn't have the option to actually implement. If you're up to the challenge to take this PR the extra mile, that will be awesome, as I believe it will be mush more used and helpful than only selecting the top half, which I think might be a little arbitrary in some cases. What do you think?
